import { defineField, defineType } from 'sanity'

export default defineType({
  name: 'project',
  title: 'Portfolio Project',
  type: 'document',
  fields: [
    defineField({
      name: 'title',
      title: 'Project Title',
      type: 'string',
      validation: (Rule) => Rule.required().min(3).max(100),
    }),
    defineField({
      name: 'slug',
      title: 'Slug (URL path)',
      type: 'slug',
      options: { source: 'title', maxLength: 96 },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'subtitle',
      title: 'Subtitle',
      type: 'string',
      description: 'Short tagline for the project',
    }),
    defineField({
      name: 'featured',
      title: 'Featured Project',
      type: 'boolean',
      description: 'Show this project in the home page featured section',
      initialValue: false,
    }),
    defineField({
      name: 'category',
      title: 'Category',
      type: 'string',
      options: {
        list: [
          { title: 'Residential', value: 'residential' },
          { title: 'Commercial', value: 'commercial' },
          { title: 'Office', value: 'office' },
          { title: 'Retail', value: 'retail' },
          { title: 'Luxury', value: 'luxury' },
          { title: 'Villa', value: 'villa' },
          { title: 'Apartment', value: 'apartment' },
          { title: 'Hospitality', value: 'hospitality' },
          { title: 'Other', value: 'other' },
        ],
        layout: 'dropdown',
      },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'tags',
      title: 'Tags',
      type: 'array',
      of: [{ type: 'string' }],
      options: { layout: 'tags' },
      description: 'e.g. Luxury, Modern, Residential',
    }),
    defineField({
      name: 'location',
      title: 'Location',
      type: 'string',
      description: 'e.g. Downtown, Dubai',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'year',
      title: 'Completion Year',
      type: 'string',
      description: 'e.g. 2025',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'area',
      title: 'Area / Size',
      type: 'string',
      description: 'e.g. 8,900 sq.ft',
    }),
    defineField({
      name: 'timeline',
      title: 'Project Timeline',
      type: 'string',
      description: 'e.g. 12 Months',
    }),
    defineField({
      name: 'scope',
      title: 'Project Scope',
      type: 'string',
      description: 'e.g. Full Interior Design, Turnkey Fitout',
    }),
    defineField({
      name: 'clientName',
      title: 'Client Name',
      type: 'string',
      description: 'Optional — leave blank for confidential clients',
    }),
    defineField({
      name: 'shortDescription',
      title: 'Short Description',
      type: 'text',
      rows: 3,
      description: 'One-paragraph summary shown on the portfolio card modal',
      validation: (Rule) => Rule.required().max(500),
    }),
    defineField({
      name: 'longDescription',
      title: 'Full Project Description',
      type: 'array',
      of: [{ type: 'block' }],
      description: 'Detailed description for the project detail page',
    }),
    defineField({
      name: 'clientBrief',
      title: 'Client Brief',
      type: 'text',
      rows: 3,
      description: 'What the client asked for',
    }),
    defineField({
      name: 'result',
      title: 'Result / Recognition',
      type: 'text',
      rows: 2,
      description: 'Awards, press mentions, or measurable outcomes',
    }),
    defineField({
      name: 'materials',
      title: 'Material Palette',
      type: 'array',
      of: [{ type: 'string' }],
      options: { layout: 'tags' },
      description: 'e.g. Calacatta Gold Marble, Smoked Oak Parquet',
    }),
    defineField({
      name: 'coverImage',
      title: 'Cover Image',
      type: 'image',
      options: { hotspot: true },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'galleryImages',
      title: 'Gallery Images',
      type: 'array',
      of: [
        {
          type: 'image',
          options: { hotspot: true },
          fields: [
            defineField({
              name: 'caption',
              title: 'Caption',
              type: 'string',
            }),
          ],
        },
      ],
      validation: (Rule) => Rule.min(1),
    }),
    defineField({
      name: 'beforeImages',
      title: 'Before Images',
      type: 'array',
      of: [{ type: 'image', options: { hotspot: true } }],
      description: 'Optional — before renovation images',
    }),
    defineField({
      name: 'afterImages',
      title: 'After Images',
      type: 'array',
      of: [{ type: 'image', options: { hotspot: true } }],
      description: 'Optional — after renovation images',
    }),
    defineField({
      name: 'videoUrl',
      title: 'Video URL',
      type: 'url',
      description: 'Optional — YouTube or Vimeo URL',
    }),
    defineField({
      name: 'seoTitle',
      title: 'SEO Title',
      type: 'string',
    }),
    defineField({
      name: 'seoDescription',
      title: 'SEO Description',
      type: 'text',
      rows: 2,
    }),
  ],
  preview: {
    select: {
      title: 'title',
      subtitle: 'location',
      media: 'coverImage',
    },
  },
  orderings: [
    {
      title: 'Newest First',
      name: 'yearDesc',
      by: [{ field: 'year', direction: 'desc' }],
    },
    {
      title: 'Featured First',
      name: 'featuredFirst',
      by: [{ field: 'featured', direction: 'desc' }],
    },
  ],
})
